- hosts: all
  vars:
      dotfiles_dir: "{{ ansible_user_dir }}/dotfiles"
  roles:
      - base
      - git
      - composer
      - dotfiles
      - vim
      - peco
      - bash
      - tmux
      - ranger

