- hosts: all
  vars:
      dotfiles_dir: "{{ ansible_user_dir }}/setup/dotfiles"
  roles:
      - base
      - git
      - php
      - role: composer
        tags: [composer]
      - dotfiles
      - vim
      - bash
      - tmux

