- name: vim package
  apt:
      name: "vim"
      state: latest
  become: true
- name: vim git repository
  git:
      repo: "{{ vim_repository }}"
      dest: "{{ vim_checkout }}"
- name: include vim config
  lineinfile:
      line: "source {{ vim_checkout }}/vimrc"
      path: "{{ ansible_user_dir }}/.vimrc"
      state: present
