---
- name: "install composer for user"
  get_url:
      url: "https://getcomposer.org/composer.phar"
      dest: "{{ ansible_user_dir }}/bin/composer"
      mode: a+x

- name: "install global composer deps"
  command: "creates={{ ansible_user_dir }}/.composer/vendor/{{ item.name }} composer global require {{ item.name }} {{ item.version }}"
  with_items:
    - { name: "asm89/twig-lint", version: "@stable"}
    - { name: "kherge/box", version: "~2.4"}
    - { name: "fabpot/php-cs-fixer", version: "^2.0"}
    - { name: "squizlabs/php_codesniffer", version: "@stable"}
    - { name: "phpmd/phpmd", version: "@stable"}
    - { name: "phpunit/phpunit", version: "@stable"}
    - { name: "pyrech/composer-changelogs", version: "^1.1"}
    - { name: "hirak/prestissimo", version: "^0.2"}
    - { name: "psy/psysh", version: "@stable"}
    - { name: "phpstan/phpstan", version: "^0.8.5"}
    - { name: "vimeo/psalm", version: "^0.3.56"}
