---
- name: "symlink gitignore"
  file:
    src: "{{ dotfiles_dir }}/gitignore"
    dest: "{{ ansible_user_dir }}/.gitignore"
    force: true
    state: link

- name: "git settings"
  git_config:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      scope: global
  with_items:
    - { key: "user.name", value: "{{ devmachine_user_name }}" }
    - { key: "user.email", value: "{{ devmachine_user_email }}" }
    - { key: "color.ui", value: auto }
    - { key: "core.editor", value: vim }
    - { key: "core.excludesfile", value: "{{ ansible_user_dir }}/.gitignore" }
    - { key: "push.default", value: "current" }
    - { key: "branch.autosetuprebase", value: always }
    - { key: "fetch.prune", value: "true" }
    - { key: "pull.rebase", value: "true" }
    - { key: "rebase.autoStash", value: "true" }
    - { key: "rerere.enabled", value: "true" }
    - { key: "diff.noprefix", value: "true" }
    - { key: "diff.colorMoved", value: plain }
    - { key: "alias.st", value: status }
    - { key: "alias.co", value: checkout }
    - { key: "alias.ci", value: commit }
    - { key: "alias.br", value: branch }
    - { key: "alias.staged", value: "diff --cached" }
    - { key: "alias.graph", value: "log --color --graph --oneline --decorate" }
    - { key: "commit.gpgsign", value: "true" }


- name: "download github-cli keyring"
  become: true
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg

- name: "install github-cli GH repository"
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present
    filename: github-gh

- name: "install github-cli GH"
  become: true
  apt:
    name: gh
    state: present
