- name: "check reqired TPM folder"
  file:
    path: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    state: directory

- name: clone TPM repository
  git:
      repo: "https://github.com/tmux-plugins/tpm"
      dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"

- name: tmux conf
  lineinfile:
    line: "source-file {{ dotfiles_dir }}/tmux-conf.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: present
    create: yes

- name: install tmux-xpanes
  get_url:
    url: "https://raw.githubusercontent.com/greymd/tmux-xpanes/v4.1.3/bin/xpanes"
    dest: "{{ ansible_user_dir }}/bin/xpanes"
    mode: 0755

