# @todo install tmux-xpanes

- name: "check reqired TPM folder"
  file:
    path: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    state: directory

- name: clone TPM repository
  git:
      repo: "https://github.com/tmux-plugins/tpm"
      dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"

- name: tmux conf
  lineinfile:
    line: "source-file {{ dotfiles_dir }}/tmux-conf.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: present
    create: yes

- name: tmux theme
  lineinfile:
    line: "source-file {{ dotfiles_dir }}/tmux-theme.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: present
