---
- name: "user bin folder exists?"
  file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory

- name: "install base packages"
  become: true
  apt:
    name:
        - curl
        - git
        - vim
        - tmux
        - silversearcher-ag
        - neofetch
        - vifm
        - tldr
        - htop
    state: present

      # needs newer ansible version or similar?
      #- name: Install snap packages
      #community.general.snap:
      #name:
      #- keepassxc
