---
- name: "use bin folder exists?"
  file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory

- name: "install base packages"
  become: true
  apt:
    name:
        - curl
        - git
        - vim
        - tmux
        - silversearcher-ag
        - neofetch
        - vifm
        - tldr
    state: present
