---
- name: extensions for {{ php_version }}
  become: true
  apt:
    name: php{{ php_version }}-{{ item }}
    state: present
  loop:
    - common
    - cli
    - fpm
    - curl
    - intl
    - mysql
    - opcache
    - zip
    - xml
    - json
    - readline
