---
- name: extensions for {{ php_version }}
  become: true
  apt:
    name:
        - php{{ php_version}}-common
        - php{{ php_version}}-cli
        - php{{ php_version}}-fpm
        - php{{ php_version}}-curl
        - php{{ php_version}}-intl
        - php{{ php_version}}-mysql
        - php{{ php_version}}-opcache
        - php{{ php_version}}-zip
        - php{{ php_version}}-xml
        - php{{ php_version}}-readline
        - php{{ php_version}}-mbstring
    state: present
