---
- name: add ppa
  become: true
  apt_repository:
    state: present
    repo: ppa:ondrej/php

- name: add base packages
  become: true
  apt:
    name:
        - php8.0
    state: present
    update_cache: true

- name: version agnostic extensions
  become: true
  apt:
    name:
        - php-memcached
    state: present

- name: extensions
  include_tasks: extensions.yml
  loop:
    - 8.0
  loop_control:
    loop_var: php_version

- name: set default version
  become: true
  alternatives:
    name: php
    path: /usr/bin/php8.0

- name: install symfony cli repo
  become: true
  apt_repository:
    repo: "deb [trusted=yes] https://repo.symfony.com/apt/ /"
    filename: symfony-cli

- name: install symfony cli
  become: true
  apt:
    name: symfony-cli
    state: present
