---
- name: add ppa
  become: true
  apt_repository:
    state: present
    repo: ppa:ondrej/php

- name: add base packages
  become: true
  apt:
    name:
        - php8.0
    state: present
    update_cache: true

- name: version agnostic extensions
  become: true
  apt:
    name:
        - php-memcached
    state: present

- name: extensions
  include_tasks: extensions.yml
  loop:
    - 8.0
  loop_control:
    loop_var: php_version

- name: set default version
  become: true
  alternatives:
    name: php
    path: /usr/bin/php8.0

- name: download symfony cli
  get_url:
      url: "https://github.com/symfony/cli/releases/download/v4.26.10/symfony_linux_amd64.gz"
      dest: "{{ ansible_user_dir }}/bin/symfony.gz"

- name: extract symfony cli
  command:
      cmd: "gunzip {{ ansible_user_dir }}/bin/symfony.gz"
      creates: "{{ ansible_user_dir }}/bin/symfony.gz"
