---
- name: add ppa
  become: true
  apt_repository:
    state: present
    repo: ppa:ondrej/php

- name: add base packages
  become: true
  apt:
    name:
        - php7.2
        - php7.3
        - php7.4
    state: present
    update_cache: true

- name: version agnostic extensions
  become: true
  apt:
    name:
        - php-memcached
    state: present

- name: extensions
  include_tasks: extensions.yml
  loop:
    - 7.3
    - 7.4
  loop_control:
    loop_var: php_version

- name: set default version
  become: true
  alternatives:
    name: php
    path: /usr/bin/php7.4

- name: install symfony cli
  get_url:
      url: "https://get.symfony.com/cli/v4.2.8/symfony_linux_amd64"
      dest: "{{ ansible_user_dir }}/bin/symfony"
      mode: 0755
      checksum: "sha256:a4ab67ca343ca0549414bfd838a73cd96a3a0ea08d7d0e18527f23e99ca7f000"
