- name: vim package
  apt:
      name: "vim"
      state: latest
  become: true

- name: vim git repository
  git:
      repo: "{{ vim_repository }}"
      dest: "{{ ansible_user_dir }}/.vim"
- name: include vim config
  lineinfile:
      line: "source {{ ansible_user_dir}}/.vim/vimrc"
      dest: "{{ ansible_user_dir }}/.vimrc"
      state: present
      create: yes
