- name: vim package
  apt:
      name: "{{ item }}"
      state: latest
  become: true
  with_items:
      - vim
      - python3-pip

- name: install python3 neovim deps
  pip:
      executable: /usr/bin/pip3
      name: "{{ item }}"
      state: present
  with_items:
      - neovim
      - jedi
      - psutil
      - setproctitle

- name: vim git repository
  git:
      repo: "{{ vim_repository }}"
      dest: "{{ ansible_user_dir }}/.vim"
- name: include vim config
  lineinfile:
      line: "source {{ ansible_user_dir}}/.vim/vimrc"
      dest: "{{ ansible_user_dir }}/.vimrc"
      state: present
      create: yes
