---
- name: "add ppa for emoji-one"
  become: true
  apt_repository:
    repo: ppa:eosrei/fonts
    update_cache: true

#- name: "add ppa for emoji-one picker"
  #become: true
  #apt_repository:
    #repo: ppa:ys/emojione-picker
    #update_cache: true

- name: "install emoji-one font"
  become: true
  apt:
    name: "{{ item }}"
  with_items:
      - fonts-emojione
      - fonts-noto-color-emoji
      #- emojione-picker

- name: "check font config folder"
  file:
    path: "{{ ansible_user_dir }}/.config/fontconfig"
    state: directory

- name: "enable font config"
  copy:
    src: "{{ dotfiles_dir }}/fonts.conf"
    dest: "{{ ansible_user_dir }}/.config/fontconfig/fonts.conf"

# @todo -> fc-cache -f -v


